import { Toaster } from 'sonner'
import './globals.css'
import type { Metadata } from 'next'
import ClientProvider from '@/provider/ClientProvider'
import CustomCursor from '@/components/Cursor'


export const metadata: Metadata = {
  title: 'JEsitiGlobal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <CustomCursor />
        <ClientProvider>
          <Toaster richColors/>
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
