import { Toaster } from 'sonner'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'JEsitiGlobal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Toaster richColors/>
        {children}
      </body>
    </html>
  )
}
